# Generated by Django 5.1.4 on 2026-10-01 10:53

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, default='Mali', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('legal_ids', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('currency_symbol', models.CharField(default='F CFA', max_length=10)),
                ('currency_decimals', models.PositiveSmallIntegerField(default=0)),
                ('timezone', models.CharField(default='Africa/Bamako', max_length=64)),
                ('locale', models.CharField(default='fr', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_roles', models.CharField(blank=True, max_length=300)),
                ('action', models.CharField(max_length=40)),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('entity_label', models.CharField(blank=True, max_length=200)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('hash_prev', models.CharField(blank=True, max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx'), models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('prefix', models.CharField(max_length=10)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'doc_type', 'year'), name='uq_doc_sequence')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Alerte'), ('danger', 'Critique')], default='info', max_length=10)),
                ('dedupe_key', models.CharField(blank=True, max_length=120)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='core_notifi_user_id_bd2d4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('store', 'Magasin'), ('warehouse', 'Entrepôt'), ('agency', 'Agence'), ('pos', 'Point de vente')], default='store', max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uq_warehouse_code')],
            },
        ),
    ]
