# Generated by Django 5.1.4 on 2026-10-01 21:22

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDevice',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_sync_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('op_id', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=30)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('done', 'Synchronisée'), ('conflict', 'Conflit à traiter'), ('rejected', 'Rejetée')], max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('conflict_reason', models.CharField(blank=True, max_length=300)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at_local', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.syncdevice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='syncdevice',
            constraint=models.UniqueConstraint(fields=('company', 'device_id'), name='uq_sync_device'),
        ),
        migrations.AddConstraint(
            model_name='syncoperation',
            constraint=models.UniqueConstraint(fields=('device', 'op_id'), name='uq_sync_op'),
        ),
    ]
