# Generated by Django 5.1.4 on 2026-10-01 10:53

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte'), ('transfer', 'Virement'), ('cheque', 'Chèque'), ('mobile_money', 'Mobile Money'), ('other', 'Autre')], max_length=15)),
                ('requires_reference', models.BooleanField(default=False)),
                ('color', models.CharField(default='#a78bfa', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RegisterSession',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_float', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected', models.JSONField(blank=True, default=dict)),
                ('counted', models.JSONField(blank=True, default=dict)),
                ('denominations', models.JSONField(blank=True, default=dict)),
                ('difference', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('difference_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Clôturée'), ('validated', 'Validée')], default='open', max_length=10)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('z_number', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('cash', 'Espèces'), ('bank', 'Banque'), ('mobile_money', 'Mobile Money'), ('cheque', 'Chèques à encaisser')], max_length=15)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('category', models.CharField(choices=[('sale', 'Encaissement vente'), ('customer_payment', 'Règlement client'), ('refund', 'Remboursement client'), ('supplier_payment', 'Paiement fournisseur'), ('expense', 'Dépense'), ('expense_reversal', 'Extourne dépense'), ('income', 'Recette diverse'), ('float', 'Fond de caisse'), ('cash_difference', 'Écart de caisse'), ('payment_reversal', 'Extourne paiement'), ('transfer', 'Transfert de fonds')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=250)),
                ('source_type', models.CharField(blank=True, max_length=30)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('source_number', models.CharField(blank=True, max_length=40)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registers', to='core.warehouse')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('number', models.CharField(blank=True, max_length=40)),
                ('expense_date', models.DateField()),
                ('type', models.CharField(choices=[('simple', 'Dépense simple'), ('advance', 'Avance'), ('reimbursement', 'Remboursement de frais')], default='simple', max_length=15)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tax_recoverable', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('payee_type', models.CharField(choices=[('supplier', 'Fournisseur'), ('employee', 'Employé'), ('free', 'Autre')], default='free', max_length=10)),
                ('payee_name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('payment_reference', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', "En attente d'approbation"), ('approved', 'Approuvée'), ('paid', 'Payée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée')], default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=250)),
                ('reject_reason', models.CharField(blank=True, max_length=250)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(blank=True, max_length=80, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='purchasing.supplier')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.warehouse')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approuvée'), ('rejected', 'Rejetée')], max_length=10)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='finance.expense')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(max_length=300, upload_to='expenses/')),
                ('thumb', models.CharField(blank=True, max_length=300)),
                ('mime', models.CharField(max_length=60)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='finance.expense')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('fixed', 'Fixe'), ('variable', 'Variable')], default='variable', max_length=10)),
                ('icon', models.CharField(default='receipt', max_length=40)),
                ('color', models.CharField(default='#f472b6', max_length=20)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('receipt_required_above', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('approval_above', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.expensecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('number', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(max_length=300)),
                ('income_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('number', models.CharField(max_length=40)),
                ('direction', models.CharField(choices=[('in', 'Encaissement'), ('out', 'Décaissement')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unallocated', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('paid_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('valid', 'Valide'), ('reversed', 'Extourné')], default='valid', max_length=10)),
                ('idempotency_key', models.CharField(blank=True, max_length=80, null=True)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('reversal_reason', models.CharField(blank=True, max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
