# Generated by Django 5.1.4 on 2026-10-01 10:53

import apps.catalog.models
import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('barcode', models.CharField(max_length=60)),
                ('factor', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('label', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(max_length=300, upload_to=apps.catalog.models.image_path)),
                ('thumbs', models.JSONField(default=dict)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Traitement'), ('ready', 'Prête'), ('failed', 'Échec')], default='ready', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=80)),
                ('rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['rate'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('is_decimal', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(default='package', max_length=40)),
                ('color', models.CharField(default='#a78bfa', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('price_type', models.CharField(max_length=20)),
                ('old_price', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('new_price', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('internal_ref', models.CharField(max_length=40)),
                ('sku', models.CharField(max_length=60)),
                ('barcode', models.CharField(blank=True, max_length=60)),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('service', 'Service')], default='simple', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('cost_last', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cost_avg', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('price_retail', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('price_wholesale', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('wholesale_min_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('promo_start', models.DateField(blank=True, null=True)),
                ('promo_end', models.DateField(blank=True, null=True)),
                ('min_stock', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('max_stock', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('track_stock', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('archived', 'Archivé')], default='active', max_length=10)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
